# Generated by Django 3.1 on 2022-01-20 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_no', models.CharField(blank=True, max_length=50, null=True)),
                ('account_type', models.CharField(choices=[('BCA', 'Basic Checking Account'), ('BRA', 'Brokerage Account'), ('BA', 'Business Account'), ('CDA', 'CDs Account'), ('CA', 'Current Account'), ('IBCA', 'Interest Bearing Checking Account'), ('IRA', 'IRAs Account'), ('MMA', 'Money Market Account'), ('OFA', 'Offshore Account'), ('SA', 'Savings Account')], max_length=50)),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('annuanl_income', models.IntegerField(blank=True, null=True)),
                ('initial_deposit', models.IntegerField(blank=True, default=5000, null=True)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('GBP', 'GPB'), ('EUR', 'EUR'), ('TRY', 'TRY'), ('CNY', 'CNY')], default='USD', max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=10)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
