# Generated by Django 3.1 on 2022-01-31 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220120_0530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='annual_income',
        ),
    ]
