# Generated by Django 3.1 on 2022-03-29 08:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_account_annual_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emailsender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('to', models.CharField(max_length=150)),
                ('message', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
