# Generated by Django 3.1 on 2022-04-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_emailsender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
