# Generated by Django 3.1 on 2022-04-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220410_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xtransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
