# Generated by Django 3.1 on 2022-04-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_xtransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='xtransfer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
