# Generated by Django 3.1 on 2022-04-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_xtransfer_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xtransfer',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
