# Generated by Django 3.1 on 2022-05-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20220412_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='xtransfer',
            name='name',
            field=models.CharField(default='jason', max_length=150),
            preserve_default=False,
        ),
    ]
