# Generated by Django 3.1 on 2022-06-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_xtransfer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsender',
            name='to',
            field=models.EmailField(max_length=150),
        ),
    ]
