# Generated by Django 3.1 on 2022-01-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220128_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
