# Generated by Django 3.1 on 2022-05-25 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_swift_codes_tax_codes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Swift_codes',
            new_name='Swift_code',
        ),
        migrations.RenameModel(
            old_name='Tax_codes',
            new_name='Tax_code',
        ),
    ]
