# Generated by Django 3.1 on 2022-05-25 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220525_1836'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Swift_code',
            new_name='SwiftCode',
        ),
        migrations.RenameModel(
            old_name='Tax_code',
            new_name='TaxCode',
        ),
    ]
