# Generated by Django 3.1 on 2022-06-02 08:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220525_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='address2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='phone2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
