# Generated by Django 3.1 on 2022-06-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220606_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='billcode',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
