# Generated by Django 3.1 on 2022-06-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_billcode_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billcode',
            name='status',
            field=models.BooleanField(default=False, help_text='Enable and Disable this Code'),
        ),
    ]
