# Generated by Django 3.1 on 2022-06-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20220606_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billcode',
            name='status',
            field=models.BooleanField(default=False, help_text="Check box to 'Enable' and Uncheck box to 'Disable' "),
        ),
    ]
