# Generated by Django 3.1 on 2022-06-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20220606_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='aboutus',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='donate',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='our_mission',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='our_vision',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='privacypolicy',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='references',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='tandc',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='what_we_do',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='youtube',
        ),
        migrations.AddField(
            model_name='setting',
            name='otp_status',
            field=models.BooleanField(default=False, help_text="Check box to 'Enable use of OTP in transfer' and Uncheck box to 'Disable use of OTP in transfer' "),
        ),
    ]
